# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build
    {{#firebase}}
    - cd functions
    - npm install
    {{/firebase}}

test:
  stage: test
  artifacts:
    paths:
      - test/unit/coverage/lcov-report
      - test/unit/karma_html
  script:
    - npm install
    - npm run unit

{{#firebase}}
deploy:
  stage: deploy
  only:
    - master
  script:
    - cd functions
    - npm install
    - npm install firebase-tools
    - ./node_modules/firebase-tools/bin/firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
{{/firebase}}